package FactoryMethod;

public class Main {

    public static void main(String[] args) {

        Restaurant mexicanRestaurant;  //Abstract factory (doesn't know what kind of pizza will be produced)
        mexicanRestaurant = new MexicanRestaurant(); // Real implementation of factory (mexican)

        Pizza pizza; //Abstract product
        pizza = mexicanRestaurant.getPizza("Cheese"); //Real product generated by factory
        System.out.println(pizza);

        Restaurant americanRestaurant = new AmericanRestaurant();
        Pizza pizza1 = americanRestaurant.getPizza("Pepperoni");
        System.out.println(pizza1);




    }


}
